module.exports = {
    port : 40000,
    proxy : 'localhost:30000',
    minify : false,
    autoprefixer : {
        browsers : ["last 2 versions", "ie 10", "ios 10", "android 4.2"],
    },
    zip_name : 'xxxxx.zip',
    encoding : "utf-8",
    dev_root : "/Users/yamaji/Works/MAMP/git/axcelwork.org/package/src/",

    paths : {
        base : '../../htdocs',
        dev : '../../src',
        release : '../../release',
        branches: '../../branches',
        dist : '../../dist',
        src : '../../src',
        assets_dir : '/assets',
        html_dir : '/html',
        stylus_dir : '/stylus',
        pcss_dir : '/pcss',
        js_dir : '/js',
        pcss : '/**/[^_]*.css',
        pcss_c : '/**/_c/*.css',
        stylus : '/**/*.styl',
        js : '/**/*.js',
        ts : '/**/*.ts',
        ejs : '/**/*.ejs',
        css : '/**/*.css',
        html : '/**/*.html',
        inc : '/**/*.inc',
        xml : '/**/*.xml',
        php : '/**/*.php',
        json : '/**/*.json',
        jpg : '/**/*.jpg',
        gif : '/**/*.gif',
        png : '/**/*.png',
        svg : '/**/*.svg',
        woff : '/**/*.woff',
        woff2 : '/**/*.woff2',
        image : '/**/image/*'
    }
};
